configfile : 'config.yaml'

#------ Rule all ------#

rule all:
  input:
    'processed_files/lungDataset1.csv',
    'processed_files/lungDataset2.csv'
    # TODO #1
    # Replace the two previous lines with a single line
    # using the snakemake syntax

    # TODO #3
    # Modify rule all to obtain the results of
    # the survival analysis for both datasets

    # TODO #4
    # Modify rule all to obtain the report
    # generated by report_analyses

#------ Data Processing ------#

rule processing:
  input:
    script = 'src/processing.R',
    dataset = 'data/{dataset}.csv'
  output:
    processed_dataset = 'processed_files/{dataset}.csv'
  shell:
    'Rscript {input.script} {input.dataset} {output.processed_dataset}'
    
#------ Data Statistics ------#

rule patients_info:
  input:
    dataset = 'processed_files/{dataset}.csv'
  output:
    'output/patients_info/{dataset}.docx',
    'output/patients_info/{dataset}.pdf'
  script:
    'src/patients_info.R'
    
#------ Survival analysis ------#

# TODO #2
# Look at the src/survival_analysis.R file
# and the report_analyses rule.
# Write a rule to obtain the output files
# used as input by report_analyses
    
#------ Report of analyses ------#

rule report_analyses:
  input:
    patients_info = expand('output/patients_info/{dataset}.pdf', dataset = config['dataset']),
    surv_analysis = expand('output/survival_analysis/{dataset}_{stratif}.pdf', dataset = config['dataset'], stratif = config['stratification'])
  output:
    'output/reports/analyses_lung_cancer.html'
  script:
    'src/analyses_pipeline.Rmd'
